yarnPath: ".yarn/releases/yarn-berry.cjs"

npmRegistries:
  "https://npm.fontawesome.com":
    npmAuthToken: "${FONTAWESOME_REGISTRY_TOKEN}"
  "https://npm.pkg.github.com":
    npmAuthToken: "${GITHUB_TOKEN}"

npmScopes:
  daangn:
    npmRegistryServer: "https://npm.pkg.github.com"
  fortawesome:
    npmRegistryServer: "https://npm.fontawesome.com"
